backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - label: 'Blog'
    name: 'blog'
    folder: 'content/blogPosts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }